install.packages(c('Rcpp', 'units', 'lattice','shiny'))
install.packages(c('sp','sf', 'rgdal', 'gdalUtils'))

# library(rgdal)
# library(plyr)
# library(dplyr)
# library(tidyverse)
# library(data.table)
# library(sf)
# library(shiny)
# library(rgdal)
# library(gdalUtils)
# library(rgdal)
# library(plyr)
# library(dplyr)
# library(tidyverse)
# library(data.table)
# library(sf)
# library(r2stl)
# library(png)
# library(imager)
# library(magick)
# library(shinycssloaders)
# library(rgl)
# library(shiny)
# library(rgdal)
# library(sf)
# library(geosphere)
# library(plyr)
# library(tidyverse)